# Generated by Django 2.1.4 on 2018-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
